#labbook makefile

pdf : lab_book.tex 
	xelatex --shell-escape lab_book.tex
#	rm -f *.log *.idx *.out *.aux *.brf *.vrb *.toc *.nav *.dvi *.snm *.bbl *.blg *.pyg.*

clean:
	rm -f *.log *.idx *.out *.aux *.brf *.vrb *.toc *.nav *.dvi *.snm *.bbl *.blg *.pyg.*

